export const INIT_DATA_PRODUCT_TYPE = 'INIT_DATA_PRODUCT_TYPE';
export const INIT_DATA_PRODUCT_BUILDPC = 'INIT_DATA_PRODUCT_BUILDPC';


// action app
export const TOOGLE_MODAL_CHOOSE_PRODUCT = 'TOOGLE_MODAL_CHOOSE_PRODUCT';
export const TOOGLE_FILTER_PRODUCT = 'TOOGLE_FILTER_PRODUCT';
export const SET_VALUE_PRODUCT_TYPE = 'SET_VALUE_PRODUCT_TYPE';
export const SET_VALUE_PRODUCT_SEARCH_KEY = 'SET_VALUE_PRODUCT_SEARCH_KEY';
export const SET_VALUE_PRODUCT_SEARCH_ATTRIBUTE = 'SET_VALUE_PRODUCT_SEARCH_ATTRIBUTE';
export const CLEAN_ALL_ACTION_SEARCH = 'CLEAN_ALL_ACTION_SEARCH';

// product data
export const INIT_PRODUCT_DATA_BY_TYPE = 'INIT_PRODUCT_DATA_BY_TYPE';

// computer building action
export const INIT_COMPUTER_BUILDING_DATA = 'INIT_COMPUTER_BUILDING_DATA';
export const SET_VALUE_COMPUTER_PRODUCT_BY_TYPE = 'SET_VALUE_COMPUTER_PRODUCT_BY_TYPE';
export const CLEAR_VALUE_COMPUTER_PRODUCT_BY_TYPE = 'CLEAR_VALUE_COMPUTER_PRODUCT_BY_TYPE';
export const SET_QUANTITY_COMPUTER_PRODUCT_BY_TYPE = 'SET_QUANTITY_COMPUTER_PRODUCT_BY_TYPE';
export const RESET_VALUE_COMPUTER_PRODUCT = 'RESET_VALUE_COMPUTER_PRODUCT';